[meta]
schema_version = "1.0"

[register]
enable_resister = true
register = "http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379"
reg_root = "/service"
register_auth = ""
register_keys = ""
enable_pull = false
enable_push = false
lease_time = 10
keep_alive = 5

[[service]]
name = "every1s-1"
schedule = "* * * * * *"
shell = "sh  tester/test_script.sh"

[[service]]
name = "every1s-2"
schedule = "* * * * * *"
shell = "sh tester/test_script.sh"
max_wait_for_next = 10

[[service]]
name = "every1s-3"
schedule = "* * * * * *"
shell = "sh tester/test_script.sh"
max_wait_for_next = 10

[[service]]
name = "every1s-4"
schedule = "* * * * * *"
shell = "sh tester/test_script.sh"
max_wait_for_next = 10

[[service]]
name = "every1s-5"
schedule = "* * * * * *"
shell = "sh tester/test_script.sh"
max_wait_for_next = 10

[[service]]
name = "every1s-6"
schedule = "* * * * * *"
shell = "sh tester/test_script.sh"
max_wait_for_next = 10

[[service]]
name = "every1s-8"
schedule = "* * * * * *"
shell = "sh tester/test_script.sh"
max_wait_for_next = 10

[[service]]
name = "every1s-9"
schedule = "* * * * * *"
shell = "sh tester/test_script.sh"
max_wait_for_next = 10

[[service]]
name = "every1s-10"
schedule = "* * * * * *"
shell = "sh tester/test_script.sh"
max_wait_for_next = 10